site_name: Scalr - Autoscaling for Clouds
repo_url: https://github.com/ngine-io/scalr
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Install: install.md
  - Configure:
      - Common: config.md
      - Policy Configs: policy_configs.md
      - Cloud Configs: cloud.md
  - Run: running.md

theme:
  name: material
  palette:
    primary: cyan
    scheme: slate
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
plugins:
  - search
