{
 "title": "Scalr",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Current Running",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scalr_current", "legendFormat": "Current Running" }
   ]
  },
  {
   "title": "Desired",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scalr_desired", "legendFormat": "Desired" }
   ]
  },
  {
   "title": "Factor",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scalr_factor", "legendFormat": "Factor" }
   ]
  },
  {
   "title": "Boundries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scalr_max", "legendFormat": "Max" },
    { "expr": "scalr_min", "legendFormat": "Min" },
    { "expr": "scalr_max_step_down", "legendFormat": "Max Step Down" },
    { "expr": "scalr_cooldown_timeout", "legendFormat": "Cooldown" }
   ]
  },
  {
   "title": "Desired / Current",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "scalr_current", "legendFormat": "Current Running" },
    { "expr": "scalr_min", "legendFormat": "Min" },
    { "expr": "scalr_max", "legendFormat": "Max" },
    { "expr": "scalr_desired", "legendFormat": "Desired " }
   ]
  },
  {
   "title": "Scaling Factor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    { "expr": "scalr_factor", "legendFormat": "Scaling Factor" }
   ]
  }
 ]
}